Repository dynaconf/dynaconf, pull requests merged in 2019-04, with the labels that each got.

#157 Logger is now cached (removed logging import time overhead)
  README.md
  docs/index.rst
  dynaconf/loaders/__init__.py
  dynaconf/utils/__init__.py
  requirements_dev.txt
Labels: Not a Bug, enhancement

#161 fix #160 - invoking directory should not be search breaking point.
  Makefile
  azure-pipelines.yml
  dynaconf/utils/__init__.py
  dynaconf/utils/files.py
  example/issues/160/.env
  example/issues/160/subfolder/.keep
  example/issues/160/test.sh
Labels: Pending Release

#162 Skip reloading envs for validators that only apply to current_env
  dynaconf/validator.py
  requirements_dev.txt
  tests/test_validators.py
Labels: Pending Release, enhancement

#164 Fix #163 Allow disabling env prefix
  Makefile
  docs/guides/configuration.md
  docs/guides/environment_variables.md
  dynaconf/loaders/env_loader.py
  example/global_env_prefix/.env
  example/global_env_prefix/app.py
  tests/test_env_loader.py
Labels: bug, enhancement

#165 Add explicit call to main() on cli.py
  dynaconf/cli.py
Labels: enhancement

#172 Fix some open file descriptors on exampls and tests
  dynaconf/cli.py
  dynaconf/loaders/ini_loader.py
  dynaconf/loaders/json_loader.py
  dynaconf/loaders/toml_loader.py
  dynaconf/loaders/yaml_loader.py
  dynaconf/utils/files.py
  example/common-encoding/program.py
  example/custom_loader/app.py
  example/custom_loader/my_custom_loader/sff_loader.py
  example/simple/app.py
  setup.py
  tests/test_cli.py
Labels: Not a Bug
